config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :themes
  resources :themes do
    resources :answers, except: [:edit, :update]
  end
  get '/themes/home', to: 'themes#home'
  post '/themes/:theme_id/answers/:id', to: 'answers#reply', as: :reply
  root 'themes#home'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :theme
  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :answer, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: { maximum: 30 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :theme
  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    nickname = auth[:info][:nickname]
    image_url = auth[:info][:image]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end

end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :set_theme, only: %i[index new create reply]
  # before_action :set_twitter_client
  require 'uri'

  def index
    if logged_in? && current_user == @theme.user
      @answers = Answer.find_by(theme_id: params[:theme_id])
    else
      redirect_to root_path, alert: 'ログインしてください'
    end
  end

  def new; end

  def create
    @answer = Answer.new(answer_params)
    @answer.attributes = {
      theme_id: params[:theme_id]
    }
    if @answer.save
      redirect_to theme_answer_path(id: @answer.id), notice: '回答を送りました。'
    else
      render :new
    end
  end

  def show
    @answer = Answer.find(params[:id])
    @theme = Theme.find(params[:theme_id])
  end

  def reply
    # ここでツイートモスルかで条件分岐
    # redirect_to themes_url, notice: "書籍を登録しました。"
    if logged_in? && current_user == @theme.user
      reply = params[:reply]
      url = request.url
      if  redirect_to "https://twitter.com/share?url=#{url}&text=#{reply}"
        # redirect_to request.referrer, notice: 'ツイートされました。'
      else
        redirect_to request.referrer, alert: 'ツイートに失敗しました。'
      end
    else
      redirect_to root_path, alert: 'ログインしてください'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_theme
    @theme = Theme.find(params[:theme_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    flash[:notice] = "ログインしました。"
    redirect_to root_path
  end

  def destroy
    reset_session
    flash[:notice] = "ログアウトしました。"
    redirect_to root_path
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  require 'uri'
  # before_action :set_twitter_client


  def home
  end

  def index
    if logged_in? 
      @themes = Theme.where(user_id: current_user).order(id: "DESC")
    else
      redirect_to root_path, alert: "ログインしてください"
    end
  end

  def new
    if logged_in?
      @theme = Theme.new
    else
      redirect_to root_path, alert: "ログインしてください"
    end
  end

  def create
    if logged_in?
      @theme = Theme.new(theme_params)
      @theme.attributes = {
        user_id: current_user.id
      }
      url = request.url
      # ここでツイートモスルかで条件分岐
      # redirect_to themes_url, notice: "書籍を登録しました。"
      if @theme.save
        # @twitter.update("#{@theme.title}\n#{url}/#{@theme.id}")
        redirect_to "https://twitter.com/share?url=#{url}/#{@theme.id}&text=#{@theme.title}"
        # redirect_to @theme, notice: "逆質問を作成しました。回答を募集しましょう！"
      else
        render :new
      end
    else
      redirect_to root_path, notice: "ログインしてください"
    end
  end

  def show
    @theme = Theme.find(params[:id])
    @answer = Answer.new
    @answers = Answer.where(theme_id: params[:id])
    @text = URI.encode_www_form_component(@theme.title)
  end

  def destroy
    if logged_in?
      @theme = Theme.find(params[:id])
      @theme.destroy
      redirect_to themes_path, notice: "削除しました。"
    else
      redirect_to root_path, notice: "ログインしてください"
    end
  end

  private

    def theme_params
      params.require(:theme).permit(:title, :description)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def default_meta_tags
    {
      site: '募集箱📦',
      title: '募集箱📦',
      reverse: true,

      charset: 'utf-8',
      description: '募集箱は質問をTwitterに投稿し、匿名で回答を募集できるサービスです。フォロワーに聞きたい質問をしてみましょう！質問が画像付きでツイートされます。',
      keywords: '募集,匿名サービス,回答,質問箱',
      canonical: request.original_url,
      separator: '|',
      # icon: [
      #   { href: image_url('favicon.ico') },
      #   { href: image_url('icon.jpg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      # ],
      og: {
        site_name: :site, # もしくは site_name: :site
        title: :title, # もしくは title: :title
        description: :description, # もしくは description: :description
        type: 'website',
        url: request.original_url,
        image: image_url('ogp_default.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@hiiiiiibi',
      }
    }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/answers/_answer.html.erb
<% @answers.each do |answer| %>
  <a href=<%= theme_answer_path(@theme, answer.id) %> class="col-6 my-1">
    <img src=<%= "https://res.cloudinary.com/hibiki/image/upload/l_text:Sawarabi%20Gothic_35:#{URI.encode_www_form_component(@theme.title)},co_rgb:FFF,y_-140,w_600,c_fit/l_text:Sawarabi%20Gothic_35:#{URI.encode_www_form_component(answer.body)},co_rgb:000,y_20,w_600,c_fit/v1569408531/ogp/ogp_answer_ewkmvp.png" %> alt="" class="col-12">
  </a>
<% end %>

app/views/answers/_form.html.erb
<!-- app/views/answers/_form.html.erb -->

<%= form_with model: [theme, answer], local: true do |form| %>
  <%= render "shared/errors", obj: answer %>
  <div class="form-group">

    <%= form.text_area :body, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit "回答", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/answers/_new.html.erb
<!-- app/views/answers/new.html.erb -->

<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">回答する</h2>
  <%= render partial: 'answers/form', locals: { theme: @theme, answer: @answer } %>
</div>

app/views/answers/new.html.erb
<!-- app/views/answers/new.html.erb -->

<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">回答する</h2>
  <%= render partial: 'form', locals: { theme: @theme, answer: @answer } %>
</div>

app/views/answers/show.html.erb
<% set_meta_tags og: { image: "https://res.cloudinary.com/hibiki/image/upload/l_text:Sawarabi%20Gothic_35:#{URI.encode_www_form_component(@theme.title)},co_rgb:FFF,y_-140,w_600,c_fit/l_text:Sawarabi%20Gothic_35:#{URI.encode_www_form_component(@answer.body)},co_rgb:000,y_20,w_600,c_fit/v1569408531/ogp/ogp_answer_ewkmvp.png" } %>

<div class="mx-auto mt-5">
  <img src=<%= "https://res.cloudinary.com/hibiki/image/upload/l_text:Sawarabi%20Gothic_35:#{URI.encode_www_form_component(@theme.title)},co_rgb:FFF,y_-140,w_600,c_fit/l_text:Sawarabi%20Gothic_35:#{URI.encode_www_form_component(@answer.body)},co_rgb:000,y_20,w_600,c_fit/v1569408531/ogp/ogp_answer_ewkmvp.png" %> alt="" class="">
  <br>
  <%= link_to '戻る', theme_path(id: @theme.id), class: "btn btn-primary my-3 ml-1" %>

<!-- reply_link -->
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">返答をツイートする</h2>
  <%= form_with(url: reply_path, method: :post, local: true) do |form| %>
    <%= render "shared/errors", obj: @answer %>
    <div class="form-group">
      <%= form.text_area :reply, rows: 10, class: "form-control" %>
    </div>
    <%= form.submit "ツイートする", class: "btn btn-primary" %>
  <% end %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156091574-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-156091574-1');
    </script>
  </head>

  <body>
    <%= render "shared/header" %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= render "shared/flash" %>
        </div>
      </div>
      <div class="row">
        <%# <div class="col-md-9 col-12"> %>
          <%# <div class="row"> %>
            <%= yield %>
          <%# </div> %>
        <%# </div> %>
      </div>
    </div>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<!-- app/views/shared/_errors.html.erb -->

<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<!-- app/views/shared/_flash.html.erb -->

<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <small>© 募集箱</small>
</div>

app/views/shared/_header.html.erb
<!-- app/views/shared/_header.html.erb -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">

  <%= link_to "募集箱", root_path, class: "navbar-brand display-1" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "過去の質問", themes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "新しい質問", new_theme_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <% if logged_in? %>
          <%= link_to 'ログアウト', logout_path, class: "nav-link" %>
        <% else %>
          <%= link_to 'Twitterでログイン', '/auth/twitter', class: "nav-link" %>
        <% end %>
      </li>
    </ul>
    <% if logged_in? %>
      <ul class="navbar-nav mt-2 mt-lg-0 float-right">

        <li class="nav-item"><img src="<%= current_user.image_url %>" alt=""></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/themes/_form.html.erb
<!-- app/views/themes/_form.html.erb -->

<%= form_with model: theme, local: true do |form| %>
  <%= render "shared/errors", obj: theme %>
  <div class="form-group">
    <%= form.label "質問のタイトル(30文字以内)(,/&の文字は使えません。)" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label "詳細(なくてもOK)" %>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit "投稿", class: "btn btn-primary btn-lg" %>
<% end %>

app/views/themes/home.html.erb
<div id="top" class="col-12">
  <h1 id= "title" class= "mx-auto">質問を投稿して<br>
  匿名回答を募集しよう！</h1>
  <h3 id= "title-sub" class= "mx-auto">Twitterで質問を投稿し、匿名の回答を募集できるサービスです。</h3>

  <% if logged_in? %>
    <%= link_to "新しい質問を作る", new_theme_path, class: "button" %>
  <% else %>
    <%= link_to 'Twitterでログイン', '/auth/twitter', class: "button" %>
  <% end %>
</div>
<%# <hr class= "lb-line1"> %>
<div id="grey-bg">
  <%= image_tag 'description.png' %>
  <%# <hr class="lb-line2"> %>
</div>

<div id="subscribe" class="col-12">
  <h2>まずはカンタン5秒で会員登録！</h2>
  <% if logged_in? %>
    <%= link_to "新しい質問を作る", new_theme_path, class: "button" %>
  <% else %>
    <%= link_to 'Twitterでログイン', '/auth/twitter', class: "button" %>
  <% end %>
</div>

app/views/themes/index.html.erb
<h1 class="col-12">過去にした質問</h1>
<% @themes.each do |theme| %>
  <div class="col-sm-12 col-lg-6 my-2">
    <%# <div class="row"> %>
      <a href="/themes/<%= theme.id %>">
        <img src=<%= "https://res.cloudinary.com/hibiki/image/upload/l_text:Sawarabi%20Gothic_35:#{URI.encode_www_form_component(theme.title)},co_rgb:000,y_-80,w_600,c_fit/v1568955978/ogp/ogpimage_pvjjw4.png" %> alt="", style="width: 100%;">
      </a>
    <%# </div> %>
  </div>
<% end %> 

app/views/themes/new.html.erb
<!-- app/views/books/new.html.erb -->

<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center">新しい質問を作る</h2>
  <%= render 'form', theme: @theme %>
</div>

app/views/themes/show.html.erb
<div class="mx-auto">
  <!-- app/views/themes/show.html.erb -->

  <% set_meta_tags og: { image: image_url("https://res.cloudinary.com/hibiki/image/upload/l_text:Sawarabi%20Gothic_35:#{@text},co_rgb:000,y_-80,w_600,c_fit/v1568955978/ogp/ogpimage_pvjjw4.png") } %>


  <div class="mt-5">
    <img src=<%= "https://res.cloudinary.com/hibiki/image/upload/l_text:Sawarabi%20Gothic_35:#{@text},co_rgb:000,y_-80,w_600,c_fit/v1568955978/ogp/ogpimage_pvjjw4.png" %> alt="">
    <hr>
    <h4>詳細</h4>
    <%= simple_format @theme.description %>
    <div class="row mt-3">
      <%= render partial: "answers/new"%>
    </div>
  <!-- answers -->
    <% if logged_in? %>
      <hr>
      <h4>回答</h4>
      <div class="row mt-3">
        <%= render partial: "answers/answer"%>
      </div>

      <%= button_tag "質問を削除する", class: "btn btn-outline-dark col-md-6 offset-md-3 mt-3", data: { toggle: "modal", target: "#delete-theme" } %>
    <% end %>
  </div>

  <div class="modal fade" id="delete-theme">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= "この質問を削除しますか？" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <!-- <div class="modal-body"> -->
        <!-- <p><%= t(".question_theme", theme: @theme.title) %></p> -->
        <!-- </div> -->
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(".chancel") %></button>
          <%= link_to t(".delete_action"), theme_path(@theme), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>